# MCP Proxy Configuration with Mock Servers
servers:
  mock-server-1:
    command: "python3"
    args: ["./mock-mcp-server.py"]
    transport:
      type: stdio
    healthCheck:
      enabled: true
      intervalSeconds: 10

  mock-server-2:
    command: "python3"
    args: ["./mock-mcp-server.py"]
    transport:
      type: stdio
    healthCheck:
      enabled: true
      intervalSeconds: 15

proxy:
  port: 3000
  host: "127.0.0.1"
  connectionPoolSize: 10
  requestTimeoutMs: 5000
  maxConcurrentRequests: 100

webUi:
  enabled: true
  port: 8081
  host: "127.0.0.1"

healthCheck:
  enabled: true
  intervalSeconds: 30
  timeoutSeconds: 5
  maxAttempts: 3
  retryIntervalSeconds: 2