# MCP Rust Proxy Configuration
# Based on MCP servers from .claude.json

servers:
  # Context7 - Library documentation server
  context7:
    command: "/nix/store/8a852rx4sw6jaqz5m7wf6rb2z63x41l8-context7-mcp-1.0.14/bin/context7-mcp"
    args: []
    env: {}
    transport:
      type: stdio
    restartOnFailure: true
    maxRestarts: 3

  # Fetch - Web content fetching
  fetch:
    command: "/nix/store/p2fsgnhjfz5a9p8fqi2ia35fca03skvw-mcp-server-fetch-2025.7.1/bin/mcp-server-fetch"
    args: []
    env: {}
    transport:
      type: stdio
    restartOnFailure: true
    # This server doesn't support ping, so disable health checks
    healthCheck:
      enabled: false

  # Filesystem - File system access
  filesystem:
    command: "/nix/store/apjxbw3ff380md24x0nmka3hi979drcr-nodejs-22.16.0/bin/npx"
    args:
      - "-y"
      - "@modelcontextprotocol/server-filesystem@latest"
      - "/Users/ztaylor/repos"
      - "/Users/ztaylor/dotfiles"
    env:
      HOME: "/Users/ztaylor"
      NODE_PATH: "/nix/store/apjxbw3ff380md24x0nmka3hi979drcr-nodejs-22.16.0/lib/node_modules"
      PATH: "/nix/store/apjxbw3ff380md24x0nmka3hi979drcr-nodejs-22.16.0/bin:/nix/store/k1ib61q5hx8sywsdjj06zjbrq5rqli3m-bash-interactive-5.2p37/bin:/usr/bin:/bin"
      XDG_CONFIG_HOME: "/Users/ztaylor/.config"
    transport:
      type: stdio
    restartOnFailure: true

  # Git - Git repository operations
  git:
    command: "/nix/store/lrsprwy6jd7q0bpb7ns336170fvib3f6-mcp-server-git-2025.7.1/bin/mcp-server-git"
    args:
      - "--repository"
      - "/Users/ztaylor/dotfiles/nix"
    env: {}
    transport:
      type: stdio
    restartOnFailure: true
    # This server doesn't support ping, so disable health checks
    healthCheck:
      enabled: false

  # GitHub - GitHub API operations
  github:
    command: "/nix/store/0qkia2x94s32qm419brv215qkm5yl6yp-github-mcp-server/bin/github-mcp-server"
    args:
      - "stdio"
    env: {}
    transport:
      type: stdio
    restartOnFailure: true
    # Example: Override health check settings for this server
    # healthCheck:
    #   intervalSeconds: 120  # Check every 2 minutes instead of default

  # Memory - Persistent memory storage
  memory:
    command: "/nix/store/syriwihrly43z3cq3665ri50cmmy9fdd-mcp-server-memory-2025.7.1/bin/mcp-server-memory"
    args: []
    env:
      MEMORY_FILE_PATH: "/Users/ztaylor/.config/memory-mcp/memory.db"
    transport:
      type: stdio
    restartOnFailure: true

  # Playwright - Browser automation
  playwright:
    command: "/nix/store/y5q7lby0c9ljw7qbfcgs2aychvcr6qcq-playwright-mcp-0.0.30/bin/mcp-server-playwright"
    args:
      - "--executable-path"
      - "/nix/store/3hdsy8q8y34nxqxd60cp8zcbjwhjx63v-google-chrome-138.0.7204.101/bin/google-chrome-stable"
    env: {}
    transport:
      type: stdio
    restartOnFailure: true
    maxRestarts: 2 # Browser processes can be resource intensive

  # Pulumi - Infrastructure as Code
  # Note: This one uses SSE transport
  pulumi:
    command: "/nix/store/rbjbrfbajkkdw5fq4s0i0iw71nwixdlx-_at_pulumi_slash_mcp-server-0.1.6/bin/mcp-server"
    args:
      - "sse"
    env: {}
    enabled: false # Disabled by default - enable when needed
    transport:
      type: httpSse
      url: "http://localhost:8080/sse" # You may need to adjust this URL
    restartOnFailure: true

  # Sequential Thinking - Advanced reasoning
  sequential-thinking:
    command: "/nix/store/33k4c3cgm9jlvh4097w05x33dp5kpc14-mcp-server-sequential-thinking-2025.7.1/bin/mcp-server-sequential-thinking"
    args: []
    env: {}
    transport:
      type: stdio
    restartOnFailure: true

  # Serena - Semantic code analysis and navigation
  serena:
    command: "/nix/store/m3im9527fy90pw0n59ba4l25bk3rd2lj-serena-mcp-launcher"
    args: []
    env:
      HOME: "/Users/ztaylor"
      PATH: "/nix/store/rjx0gy4cl4wp2wmibkb3yjpzw8kb7rk6-uv-0.7.22/bin:/nix/store/v21kg4vm7yy0wflh0avkibz0shk86jn8-python3-3.12.11/bin:/nix/store/sn3k53wdfngc737bkci111ic8psm7jn8-git-2.50.1/bin:/nix/store/1n6wb8x5dw1q5wdyws70myxr1397g0jd-rust-default-1.88.0/bin:/nix/store/20iv68w4k1vvjh18xxysjihfm02vq53k-rust-analyzer-2025-07-28/bin:/nix/store/apjxbw3ff380md24x0nmka3hi979drcr-nodejs-22.16.0/bin:/nix/store/7712hv9svx4cf3cc5g848aa073aak0a4-coreutils-9.7/bin:/usr/bin:/bin"
    enabled: true
    transport:
      type: stdio
    restartOnFailure: true
    healthCheck:
      enabled: false # Disable health checks - Serena doesn't support ping

  # Time - Time and timezone utilities
  time:
    command: "/nix/store/blkyfy6pa9xkfzvqkpkhvhgk59wzbmrs-mcp-server-time-2025.7.1/bin/mcp-server-time"
    args: []
    env: {}
    transport:
      type: stdio
    restartOnFailure: true
    # This server doesn't support ping, so disable health checks
    healthCheck:
      enabled: false

# Proxy configuration
proxy:
  port: 3000
  host: "0.0.0.0"
  connectionPoolSize: 10
  requestTimeoutMs: 30000
  maxConcurrentRequests: 100

# Web UI configuration
webUi:
  enabled: true
  port: 3001
  host: "0.0.0.0"
  # Uncomment to add authentication
  # apiKey: "${WEB_UI_API_KEY}"

# Global health check configuration
# These are defaults that can be overridden per server
healthCheck:
  enabled: true # Enable by default, can be disabled per server
  intervalSeconds: 60 # Check every minute
  timeoutSeconds: 5
  maxAttempts: 3 # Try 3 times before marking as unhealthy
  retryIntervalSeconds: 10 # Wait 10 seconds between retry attempts

# AI Context Tracing Configuration
# Enables LLM agents to track provenance and submit quality feedback
contextTracing:
  enabled: true
  storageType: hybrid # hybrid (DashMap + SQLite) or sqliteOnly
  sqlitePath: /Users/ztaylor/.mcp-proxy/context-tracing.db
  cacheSize: 10000 # Max items in memory cache
  cacheTtlSeconds: 604800 # 7 days
  retentionDays: 90 # Delete data older than 90 days

# JavaScript Plugin System Configuration
# Official plugins for security and content optimization
plugins:
  pluginDir: ./src/plugins/official # Official maintained plugins
  nodeExecutable: node
  maxConcurrentExecutions: 20 # Concurrent plugin processes
  poolSizePerPlugin: 10 # Warm processes per plugin
  defaultTimeoutMs: 30000 # 30 second default timeout

  servers:
    # Aggregator - Multi-server context optimization (special handling)
    aggregator:
      response:
        - name: aggregator-plugin
          order: 1
          enabled: true # Enable when ANTHROPIC_API_KEY is set
          timeoutMs: 60000 # 60 seconds for aggregation (Claude + MCP servers need time)

    # Context7 - AI-powered curation + prompt injection protection
    context7:
      response:
        - name: curation-plugin
          order: 1
          enabled: true # Enable when ANTHROPIC_API_KEY is set
          timeoutMs: 60000
        - name: prompt-injection-scanner
          order: 2
          enabled: true # Response security scanning
          timeoutMs: 5000

    # Filesystem - Request security validation
    filesystem:
      request:
        - name: security-plugin
          order: 1
          enabled: true # Block sensitive data in requests
          timeoutMs: 5000

# Environment variables:
# - ANTHROPIC_API_KEY: Required for aggregator and curation plugins
