# Full Plugin System Example Configuration
#
# This example demonstrates a complete plugin setup with multiple servers
# and different plugin configurations.

# MCP Server Configuration
servers:
  context7:
    command: npx
    args:
      - -y
      - "@context7/mcp-server"
    env:
      CONTEXT7_API_KEY: "${CONTEXT7_API_KEY}"
    transport:
      type: stdio

  filesystem:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - "/Users/yourname/Documents"
    transport:
      type: stdio

# Proxy Configuration
proxy:
  host: "0.0.0.0"
  port: 3000
  connectionPoolSize: 10
  requestTimeoutMs: 30000
  maxConcurrentRequests: 100

# Web UI Configuration
webUi:
  enabled: true
  host: "0.0.0.0"
  port: 3001

# Plugin System Configuration
plugins:
  # Global plugin settings
  pluginDir: ./examples/plugins
  nodeExecutable: node
  maxConcurrentExecutions: 10
  poolSizePerPlugin: 5
  defaultTimeoutMs: 30000

  # Server-specific plugin assignments
  servers:
    # Context7: Apply curation to reduce documentation size
    context7:
      response:
        - name: curation-plugin
          order: 1
          enabled: true
          timeoutMs: 45000  # AI calls need more time

    # Filesystem: Security validation on requests
    # (Note: Security plugins will be added in Phase 4)
    # filesystem:
    #   request:
    #     - name: security-plugin
    #       order: 1
    #       enabled: true
    #   response:
    #     - name: path-normalizer
    #       order: 1
    #       enabled: true

# Health Check Configuration
healthCheck:
  enabled: true
  intervalSeconds: 30
  timeoutSeconds: 5

# Context Tracing Configuration
contextTracing:
  enabled: true
  storageType: hybrid
